services:
  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile.gpu
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    gpus: all

  backend-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.gpu
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    gpus: all
